### PR TITLE
Update zh-cn language and add UPS States flag

### PR DESCRIPTION
**Pull request by MaxMadcc**
- Update Language (zh-cn).
- Fix some translations.

- Add ECO flag.
- Add RB flag.

### CODE REVIEW

**Comment by gbakeman** [comment]
I apologize for you having to update the labels relating to the Polling interval - I realized users may prefer it being in seconds rather than milliseconds, so I may need you to update that again soon. But I'll merge this in now. Good work, thank you!

**Comment by gbakeman** [comment]
@MaxMadcc Question for you:

My Visual Studio client persistently wants to reverse some of the changes you made in [this commit](https://github.com/nutdotnet/WinNUT-Client/pull/152/commits/bce79f26f8eb3ca1c2637922d19760119af3135d), do you happen to know why? For example, here's WinNUT.zh-CN.resx:

image

No matter how much I discard the changes, Visual Studio tries to make them again. Do you know if your IDE made the first set of changes automatically too? Do you think it would break anything if I accepted the changes that my IDE wants to make?

**Comment by MaxMadcc** [comment]
> @MaxMadcc Question for you:
> 
> My Visual Studio client persistently wants to reverse some of the changes you made in [this commit](https://github.com/nutdotnet/WinNUT-Client/pull/152/commits/bce79f26f8eb3ca1c2637922d19760119af3135d), do you happen to know why? For example, here's WinNUT.zh-CN.resx:
> 
> image
> 
> No matter how much I discard the changes, Visual Studio tries to make them again. Do you know if your IDE made the first set of changes automatically too? Do you think it would break anything if I accepted the changes that my IDE wants to make?

Look like my bad. :astonished:
I remember I use [ResXResourceManager](https://github.com/dotnet/ResXResourceManager) easy to fix translation. It will sync between ResX and Xliff resource files.The content on the image was generated by [ResXResourceManager](https://github.com/dotnet/ResXResourceManager). 
I took a look, it's okay to delete it.

**Comment by gbakeman** [comment]
OK, thanks for confirming and thank you again for your contributions.

**Pull request merged**
